# Generated by Django 5.1.6 on 2025-02-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
